### ISSUE TITLE
Pre-deployment checklist

### ISSUE THREAD

**Issue by philcable** [washingtonstateuniversity/finaid.wsu.edu#1]
- [ ] Implement homepage design and functionality 
  - [x] 5 easy steps (Green?)
  - [x] Calendar
  - [ ] Interactive contact map with locations
  - [x] Contact/question form
  - [x] Responsive styling
  - [x] Fun stuff for top section
- [ ] Check that content is complete/accurate & within the new framework layout
  - [ ] See ‘tertiary’ and ‘interior’ page .pdf mocks
- [x] Fat footer design and implementation via Dallen’s content
- [x] Implement scholarships landing page design
- [ ] Stylize forms for COA, Aid Estimator, Scholarships, etc.
- [x] Add transition to side right CTA buttons
- [ ] Tweak H elements, link styles, etc
- [ ] Check for mobile and tablet responsiveness
- [x] Re-work construction of top featured sections
- [x] Implement contact & forms links into top area (if not in fat-footer)
- [x] Integrate custom CSS and JS into the theme
- [ ] Write up documentation outlining the different parts of the header
- [x] Fix home page event styling in Firefox
